version: '3.8'

services:
  model-api:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - MODEL_PATH=models/model.pkl
    volumes:
      - ./models:/app/models:ro
      - ./data/processed:/app/data/processed:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    restart: unless-stopped

  mlflow:
    image: python:3.10
    working_dir: /app
    volumes:
      - ./mlruns:/app/mlruns
    ports:
      - "5001:5000"
    command: bash -c "pip install mlflow && mlflow ui --host 0.0.0.0 --port 5000"
    restart: unless-stopped
